export const seedLeads = [
  {
    source: 'line',
    channelRef: '@line_sukhumvit71',
    status: 'new',
    score: 85,
    interest: {
      products: ['ปูนซีเมนต์ SCG ตราช้าง ถุง 50 กก.', 'เหล็กข้ออ้อย DB12'],
      description: 'โครงการสร้างทาวน์โฮม 8 ยูนิต ซอยสุขุมวิท 71 ต้องการปูนโครงสร้าง 1,200 ถุง + เหล็ก 15 ตัน',
      siteLocation: 'สุขุมวิท 71 พระโขนง กทม.',
    },
    budgetRangeMinSatang: 50000000,
    budgetRangeMaxSatang: 120000000,
  },
  {
    source: 'store',
    channelRef: 'BR-BANGNA-01',
    status: 'site_visit_requested',
    score: 95,
    interest: {
      products: ['กระเบื้องหลังคาลอนคู่ SCG', 'ฉนวนกันความร้อนแผ่น 2 นิ้ว'],
      description: 'ปรับปรุงหลังคาโรงงานและติดตั้งฉนวนกันความร้อน 2,400 ตร.ม. ขอนัดช่างสำรวจหน้างานด่วน',
      siteLocation: 'กิ่งแก้ว บางพลี สมุทรปราการ',
    },
    budgetRangeMinSatang: 30000000,
    budgetRangeMaxSatang: 60000000,
  },
  {
    source: 'phone',
    channelRef: '081-987-6543',
    status: 'quoted',
    score: 90,
    interest: {
      products: ['เหล็กกล่อง 2x4 นิ้ว', 'แผ่นไม้อัด 4x8 ฟุต', 'สีทาภายนอก TOA ซุปเปอร์ชิลด์'],
      description: 'งานโครงสร้างอาคารพาณิชย์ 4 ชั้น ส่งใบเสนอราคาเรียบร้อย รอฝ่ายจัดซื้ออนุมัติ',
      siteLocation: 'ถนนราชพฤกษ์ นนทบุรี',
    },
    budgetRangeMinSatang: 80000000,
    budgetRangeMaxSatang: 150000000,
  },
  {
    source: 'other',
    channelRef: 'AE-DIRECT-04',
    status: 'won',
    score: 100,
    interest: {
      products: ['ปูนซีเมนต์ SCG ตราช้าง ถุง 50 กก.', 'อิฐมวลเบา SCG', 'ทรายหยาบ'],
      description: 'สัญญาจัดซื้อรายเดือน โครงการหมู่บ้านจัดสรร 50 หลังคาเรือน แปลงเป็นคำสั่งซื้อแล้ว',
      siteLocation: 'บางบัวทอง นนทบุรี',
    },
    budgetRangeMinSatang: 200000000,
    budgetRangeMaxSatang: 500000000,
  },
  {
    source: 'line',
    channelRef: '@line_somchai_home',
    status: 'contacted',
    score: 70,
    interest: {
      products: ['สีทาภายนอก TOA ซุปเปอร์ชิลด์', 'สีรองพื้นปูน TOA'],
      description: 'ทาสีบ้านเดี่ยว 2 ชั้น เนื้อที่ 80 ตร.ว. กำลังส่งแคตตาล็อกเฉดสีและราคาเฉลี่ย',
      siteLocation: 'รามอินทรา 65 กทม.',
    },
    budgetRangeMinSatang: 5000000,
    budgetRangeMaxSatang: 15000000,
  },
  {
    source: 'store',
    channelRef: 'BR-RATTANA-02',
    status: 'qualified',
    score: 80,
    interest: {
      products: ['ท่อ PVC ชั้น 8.5 ขนาด 4 นิ้ว', 'ซิลิโคนยาแนวกันน้ำ GE'],
      description: 'งานระบบสุขาภิบาลและประปา อาคารหอพักนักศึกษา 5 ชั้น กำลังสรุปจำนวนท่อและข้อต่อ',
      siteLocation: 'บางซื่อ กทม.',
    },
    budgetRangeMinSatang: 20000000,
    budgetRangeMaxSatang: 40000000,
  },
]
