export const seedLeads = [
  // ─── Group 1: Won Deals (C001 - C006) ────────────────────────────────────
  {
    customerCode: 'C001',
    source: 'line',
    channelRef: '@line_wiwat_const',
    status: 'won',
    score: 100,
    interest: {
      products: ['ปูนซีเมนต์ SCG ตราช้าง ถุง 50 กก.', 'เหล็กข้ออ้อย DB12', 'อิฐมวลเบา SCG'],
      description: 'โครงการสร้างทาวน์โฮม 8 ยูนิต ซอยสุขุมวิท 71 สั่งซื้อวัสดุโครงสร้างครบวงจรและส่งมอบเรียบร้อย',
      siteLocation: 'สุขุมวิท 71 พระโขนง กทม.',
    },
    budgetRangeMinSatang: 50000000,
    budgetRangeMaxSatang: 120000000,
  },
  {
    customerCode: 'C002',
    source: 'store',
    channelRef: 'BR-BANGNA-01',
    status: 'won',
    score: 95,
    interest: {
      products: ['กระเบื้องหลังคาลอนคู่ SCG', 'ฉนวนกันความร้อนแผ่น 2 นิ้ว', 'ซิลิโคนยาแนวกันน้ำ'],
      description: 'ปรับปรุงหลังคาโรงงาน 2,400 ตร.ม. ยืนยันใบเสนอราคาและออกใบส่งของเรียบร้อย',
      siteLocation: 'กิ่งแก้ว บางพลี สมุทรปราการ',
    },
    budgetRangeMinSatang: 30000000,
    budgetRangeMaxSatang: 60000000,
  },
  {
    customerCode: 'C003',
    source: 'phone',
    channelRef: '081-987-6543',
    status: 'won',
    score: 98,
    interest: {
      products: ['เหล็กกล่อง 2x4 นิ้ว', 'แผ่นไม้อัด 4x8 ฟุต', 'สีทาภายนอก TOA ซุปเปอร์ชิลด์'],
      description: 'อาคารพาณิชย์ 4 ชั้น ราชพฤกษ์ วางบิลเครดิตเทอม 45 วันและจัดส่งสินค้าล็อตหลักแล้ว',
      siteLocation: 'ถนนราชพฤกษ์ นนทบุรี',
    },
    budgetRangeMinSatang: 80000000,
    budgetRangeMaxSatang: 150000000,
  },
  {
    customerCode: 'C004',
    source: 'other',
    channelRef: 'AE-DIRECT-01',
    status: 'won',
    score: 95,
    interest: {
      products: ['เหล็กข้ออ้อย DB20', 'ปูนโครงสร้าง SCG ผสมเสร็จ', 'นั่งร้านเหล็กกัลวาไนซ์'],
      description: 'โครงการคอนโดมิเนียม ริมแม่น้ำเจ้าพระยา จัดส่งล็อตฐานรากเสร็จสิ้น',
      siteLocation: 'ถนนเจริญนคร คลองสาน กทม.',
    },
    budgetRangeMinSatang: 250000000,
    budgetRangeMaxSatang: 450000000,
  },
  {
    customerCode: 'C005',
    source: 'other',
    channelRef: 'AE-DIRECT-02',
    status: 'won',
    score: 100,
    interest: {
      products: ['กระเบื้องแกรนิตโต้ 60x60', 'สุขภัณฑ์ COTTO', 'สีทาภายใน TOA Duraclean'],
      description: 'งานตกแต่งภายในโครงการคอนโด อนันดา สเปซ พระราม 9 ปิดการขายแล้ว',
      siteLocation: 'ถนนพระราม 9 ห้วยขวาง กทม.',
    },
    budgetRangeMinSatang: 300000000,
    budgetRangeMaxSatang: 600000000,
  },
  {
    customerCode: 'C006',
    source: 'web',
    channelRef: 'WEB-FORM-089',
    status: 'won',
    score: 90,
    interest: {
      products: ['แผ่นยิปซั่ม ตราช้าง 9 มม.', 'โครงคร่าวซีลายน์ C-Line', 'โคมไฟดาวน์ไลท์ LED'],
      description: 'งานกั้นห้องและฝ้าเพดาน ออฟฟิศสาทรสแควร์ ชั้น 28 ปิดดีลเรียบร้อย',
      siteLocation: 'อาคารสาทรสแควร์ บางรัก กทม.',
    },
    budgetRangeMinSatang: 20000000,
    budgetRangeMaxSatang: 40000000,
  },

  // ─── Group 2: Pipeline / In-Progress (C007 - C013) ───────────────────────
  {
    customerCode: 'C007',
    source: 'store',
    channelRef: 'BR-CHAENGWATTANA-01',
    status: 'quoted',
    score: 85,
    interest: {
      products: ['ปูนซีเมนต์ SCG', 'อิฐมวลเบา 10 ซม.', 'เหล็กเส้นกลม RB9'],
      description: 'โครงการทาวน์โฮม 12 ยูนิต แจ้งวัฒนะ ส่งใบเสนอราคา QT-202609-0004 แล้ว รอฝ่ายจัดซื้ออนุมัติ',
      siteLocation: 'ถนนแจ้งวัฒนะ ปากเกร็ด นนทบุรี',
    },
    budgetRangeMinSatang: 70000000,
    budgetRangeMaxSatang: 100000000,
  },
  {
    customerCode: 'C008',
    source: 'phone',
    channelRef: '089-555-1234',
    status: 'quoted',
    score: 80,
    interest: {
      products: ['แผ่นเมทัลชีท บลูสโคป 0.47 มม.', 'ฉนวน PE กันความร้อน', 'เสาเหล็ก Wide Flange'],
      description: 'ก่อสร้างคลังสินค้า บางนา กม.19 เสนอราคาเรียบร้อย ลูกค้าขอต่อรองส่วนลดพิเศษ 3%',
      siteLocation: 'บางนา-ตราด กม.19 สมุทรปราการ',
    },
    budgetRangeMinSatang: 120000000,
    budgetRangeMaxSatang: 180000000,
  },
  {
    customerCode: 'C009',
    source: 'line',
    channelRef: '@line_bkk_property',
    status: 'site_visit_requested',
    score: 85,
    interest: {
      products: ['ท่อระบายน้ำ คสล. ขนาด 0.60 ม.', 'บ่อพักสำเร็จรูป', 'ฝาท่อเหล็กหล่อ'],
      description: 'ระบบระบายน้ำและสุขาภิบาลโครงการบ้านจัดสรร บางใหญ่ ขอนัดช่างสำรวจหน้างานเพื่อประเมินระยะท่อ',
      siteLocation: 'กาญจนาภิเษก บางใหญ่ นนทบุรี',
    },
    budgetRangeMinSatang: 150000000,
    budgetRangeMaxSatang: 250000000,
  },
  {
    customerCode: 'C010',
    source: 'store',
    channelRef: 'BR-PHITSANULOK-01',
    status: 'qualified',
    score: 75,
    interest: {
      products: ['กระเบื้องหลังคาเซรามิค SCG Excella', 'ไม้ฝา เฌอร่า 6 นิ้ว', 'สีรองพื้นปูนเก่า'],
      description: 'โครงการคอมมูนิตี้พลาซ่า เมืองพิษณุโลก ผ่านการคัดกรองเบื้องต้น กำลังรอนัดคิวสำรวจหน้างาน',
      siteLocation: 'ถนนสิงหวัฒน์ เมือง พิษณุโลก',
    },
    budgetRangeMinSatang: 30000000,
    budgetRangeMaxSatang: 50000000,
  },
  {
    customerCode: 'C011',
    source: 'phone',
    channelRef: '053-567-8901',
    status: 'contacted',
    score: 65,
    interest: {
      products: ['เหล็กรูปพรรณ SS400', 'ลวดเชื่อม KOBE', 'สีกันสนิมรองพื้น'],
      description: 'ผู้รับเหมาภาคเหนือสอบถามราคาเหล็กโครงสร้างล็อตใหญ่ เซลล์ติดต่อกลับและส่งแคตตาล็อกราคาแล้ว',
      siteLocation: 'ถนนซุปเปอร์ไฮเวย์ เชียงใหม่-ลำปาง',
    },
    budgetRangeMinSatang: 15000000,
    budgetRangeMaxSatang: 30000000,
  },
  {
    customerCode: 'C012',
    source: 'other',
    channelRef: 'AE-DIRECT-03',
    status: 'quoted',
    score: 88,
    interest: {
      products: ['กระจกเขียวตัดแสง 6 มม.', 'อลูมิเนียมเส้น อบขาว 1.5 มม.', 'อุปกรณ์บานเลือง Hafele'],
      description: 'งานกระจกและอลูมิเนียม อาคารสำนักงาน 5 ชั้น เซลล์กำลังจัดทำใบเสนอราคาฉบับแก้ไข',
      siteLocation: 'ถนนพหลโยธิน จตุจักร กทม.',
    },
    budgetRangeMinSatang: 60000000,
    budgetRangeMaxSatang: 90000000,
  },
  {
    customerCode: 'C013',
    source: 'store',
    channelRef: 'BR-RAMA2-01',
    status: 'site_visit_requested',
    score: 80,
    interest: {
      products: ['อิฐบล็อกประสาน', 'หินคลุก', 'แผ่น Geotextile'],
      description: 'งานปรับพื้นและลาดจอดรถโรงงาน เอกชัย ช่างสำรวจหน้างานแล้ว อยู่ระหว่างคำนวณปริมาตรหินคลุก',
      siteLocation: 'ถนนพระราม 2 บางขุนเทียน กทม.',
    },
    budgetRangeMinSatang: 20000000,
    budgetRangeMaxSatang: 35000000,
  },

  // ─── Group 3: Early Discovery / New Leads (C014 - C016) ──────────────────
  {
    customerCode: 'C014',
    source: 'line',
    channelRef: '@line_somchai_home',
    status: 'new',
    score: 60,
    interest: {
      products: ['สีทาภายนอก TOA ซุปเปอร์ชิลด์', 'ปูนฉาบผิวบาง สกิมโค้ท'],
      description: 'ติดต่อผ่าน LINE OA สอบถามราคาสีและโปรโมชั่นจัดส่งฟรีหน้างานบ้านเดี่ยว',
      siteLocation: 'รามอินทรา 65 บางเขน กทม.',
    },
    budgetRangeMinSatang: 5000000,
    budgetRangeMaxSatang: 12000000,
  },
  {
    customerCode: 'C015',
    source: 'store',
    channelRef: 'BR-BANGBUATHONG-01',
    status: 'new',
    score: 70,
    interest: {
      products: ['ท่อ PVC ตราช้าง 4 นิ้ว', 'ถังเก็บน้ำบนดิน DOS 2,000L', 'ปั๊มน้ำ Grundfos'],
      description: 'ลูกค้าโครงการบ้านเดี่ยว Walk-in สาขาบางบัวทอง แจ้งความต้องการระบบประปา 15 หลัง',
      siteLocation: 'ถนนชัยพฤกษ์ บางบัวทอง นนทบุรี',
    },
    budgetRangeMinSatang: 35000000,
    budgetRangeMaxSatang: 50000000,
  },
  {
    customerCode: 'C016',
    source: 'web',
    channelRef: 'WEB-FORM-099',
    status: 'new',
    score: 75,
    interest: {
      products: ['คอนกรีตผสมเสร็จ 280 ksc', 'เหล็ก Wire Mesh 6 มม.', 'น้ำยาประสานคอนกรีต'],
      description: 'กรอกแบบฟอร์มผ่านเว็บ ขอใบเสนอราคาเทพื้นลานกระจายสินค้า 5,000 ตร.ม.',
      siteLocation: 'นิคมอุตสาหกรรมแหลมฉบัง ชลบุรี',
    },
    budgetRangeMinSatang: 50000000,
    budgetRangeMaxSatang: 80000000,
  },

  // ─── Group 4: Closed Lost / No Purchase (C017 - C020) ────────────────────
  {
    customerCode: 'C017',
    source: 'phone',
    channelRef: '02-934-5678',
    status: 'lost',
    score: 30,
    interest: {
      products: ['เสาเข็มไอ คอรอน 0.22x0.22 ม.', 'ปูนเกร้าท์แรงสูง Sika'],
      description: 'เสนอราคาโครงการฐานราก เสียดีลให้คู่แข่งท้องถิ่นเนื่องจากราคาคู่แข่งต่ำกว่า 5%',
      siteLocation: 'ถนนร่มเกล้า ลาดกระบัง กทม.',
    },
    budgetRangeMinSatang: 10000000,
    budgetRangeMaxSatang: 20000000,
  },
  {
    customerCode: 'C018',
    source: 'other',
    channelRef: 'AE-DIRECT-05',
    status: 'lost',
    score: 20,
    interest: {
      products: ['เหล็กโครงสร้าง H-Beam', 'สลิงดึงโครงหลังคา', 'น็อตแรงดึงสูง High Tensile Bolt'],
      description: 'ส่งใบเสนอราคา QT-202608-0099 หมดอายุ ลูกค้าแจ้งชะลอการลงทุนสร้างโกดังใหม่ไม่มีกำหนด',
      siteLocation: 'ถนนเพชรเกษม กระทุ่มแบน สมุทรสาคร',
    },
    budgetRangeMinSatang: 18000000,
    budgetRangeMaxSatang: 30000000,
  },
  {
    customerCode: 'C019',
    source: 'line',
    channelRef: '@line_wichai_renovate',
    status: 'lost',
    score: 15,
    interest: {
      products: ['กระเบื้องปูพื้น 30x30 (10 กล่อง)', 'ปูนกาว Weber (5 ถุง)'],
      description: 'Disqualified: ปริมาณสั่งซื้อต่ำกว่าขั้นต่ำขายส่ง B2B (MOQ) แนะนำลูกค้าซื้อที่หน้าร้านไทวัสดุสาขาใกล้เคียง',
      siteLocation: 'อ่อนนุช 44 พระโขนง กทม.',
    },
    budgetRangeMinSatang: 1000000,
    budgetRangeMaxSatang: 3000000,
  },
  {
    customerCode: 'C020',
    source: 'store',
    channelRef: 'BR-RANGSIT-01',
    status: 'lost',
    score: 25,
    interest: {
      products: ['รางยึดแผงโซลาร์เซลล์ อลูมิเนียม', 'สายไฟ Solar Cable 4 sq.mm.'],
      description: 'สำรวจหน้างานแล้ว แต่ลูกค้าแจ้งตัดงบประมาณพลังงานสะอาดปี 2026 ขอยกเลิกโครงการชั่วคราว',
      siteLocation: 'รังสิต-นครนายก คลอง 4 ปทุมธานี',
    },
    budgetRangeMinSatang: 12000000,
    budgetRangeMaxSatang: 25000000,
  },
]
